# Google App Engine configuration
runtime: python310
entrypoint: gunicorn --config gunicorn.conf.py wsgi:application

instance_class: F2

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10
  min_pending_latency: 30ms
  max_pending_latency: automatic
  max_concurrent_requests: 50

env_variables:
  FLASK_ENV: 'production'
  ORBCOMM_DATA_DIR: '/tmp/orbcomm'
  LOG_LEVEL: 'INFO'
  METRICS_ENABLED: 'true'

# Environment variables from Secret Manager
# Set these in Google Cloud Console
# SECRET_KEY: secret(SECRET_KEY)
# DATABASE_URL: secret(DATABASE_URL)

handlers:
  - url: /static
    static_dir: static
    secure: always
    redirect_http_response_code: 301

  - url: /.*
    script: auto
    secure: always
    redirect_http_response_code: 301
