apiVersion: apps/v1
kind: Deployment
metadata:
  name: orbcomm-tracker
  labels:
    app: orbcomm-tracker
    version: v1.1.0
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: orbcomm-tracker
  template:
    metadata:
      labels:
        app: orbcomm-tracker
        version: v1.1.0
    spec:
      containers:
      - name: orbcomm-tracker
        image: gcr.io/PROJECT_ID/orbcomm-tracker:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
          name: http
          protocol: TCP
        env:
        - name: FLASK_ENV
          value: "production"
        - name: ORBCOMM_DATA_DIR
          value: "/app/data"
        - name: LOG_LEVEL
          value: "INFO"
        - name: METRICS_ENABLED
          value: "true"
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: orbcomm-secrets
              key: secret-key
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: orbcomm-secrets
              key: database-url
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health/live
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health/ready
            port: 5000
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        volumeMounts:
        - name: orbcomm-data
          mountPath: /app/data
      volumes:
      - name: orbcomm-data
        persistentVolumeClaim:
          claimName: orbcomm-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: orbcomm-tracker
  labels:
    app: orbcomm-tracker
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 5000
    protocol: TCP
    name: http
  selector:
    app: orbcomm-tracker
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: orbcomm-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard
---
apiVersion: v1
kind: Secret
metadata:
  name: orbcomm-secrets
type: Opaque
stringData:
  secret-key: "REPLACE_WITH_YOUR_SECRET_KEY"
  database-url: "REPLACE_WITH_YOUR_DATABASE_URL"
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: orbcomm-tracker-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: orbcomm-tracker
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
